### PR TITLE
added feature custom connection callback.

### PR DESCRIPTION
**Pull request by nobonobo**
usage example

``` go
package main

import (
    "database/sql"
    "fmt"
    "github.com/mxk/go-sqlite/sqlite3"
)

func main() {
    sql.Register("sqlite3-hook", &sqlite3.Driver{func(conn *sqlite3.Conn) error {
        fmt.Println("connect:", conn)
        if err := conn.Exec("pragma journal_mode=WAL;" +
            "pragma read_uncommitted=true;" +
            "pragma locking_mode=NORMAL;" +
            "pragma synchronous=FULL;" +
            "pragma busy_timeout=60000;" +
            "pragma cache_spill=true;"); err != nil {
            return err
        }
        return nil
    }})
    db, err := sql.Open("sqlite3-hook", "file:db.sqlite3")
    fmt.Println(db, err)
}
```

### CODE REVIEW

**Comment by mxk** [comment]
Are there any other database/sql drivers that provide this functionality? I don't really like this idea, because when using database/sql, you should import the package with the blank identifier, as in `import _ "github.com/mxk/go-sqlite/sqlite3"`. What is the advantage of this approach instead of having a separate function that calls sql.Open("sqlite3", ...) followed by conn.Exec(...)?

**Comment by nobonobo** [comment]
In other implementations: https://github.com/mattn/go-sqlite3/blob/master/_example/hook/hook.go

"database/sql" package will create many connections（connection-pool）.
"normal procedure" will be affected first connection only.

For example, when running multiple transaction(more than 5 seconds),
This operation will be time-out error. 

I want customize settings for each of connection.

**Comment by mxk** [comment]
Give me a couple of days to think about this. My other concern is that sqlite3.Driver was exported as a string type, making this a backward-incompatible change.

**Comment by mxk** [comment]
There is a better way of doing this. Just wrap sqlite3.Driver with your own driver.Driver implementation, as in the example below. This gives you more flexibility and doesn't require any changes to the sqlite3 package. You can even define SQLiteHook as `func (c driver.Conn) error` and then move the initialization code to the `sql.Register` call.

``` go
package main

import (
    "database/sql"
    "database/sql/driver"
    "fmt"

    "github.com/mxk/go-sqlite/sqlite3"
)

type SQLiteHook struct{}

func (SQLiteHook) Open(name string) (driver.Conn, error) {
    fmt.Println("open")
    c, err := sqlite3.Driver("sqlite3-hook").Open(name)
    if err == nil {
        _, err = c.(driver.Execer).Exec(`
            pragma locking_mode=NORMAL;
            pragma synchronous=FULL;
            pragma busy_timeout=60000;
        `, nil)
        if err != nil {
            c.Close()
            c = nil
        }
    }
    return c, err
}

func main() {
    sql.Register("sqlite3-hook", SQLiteHook{})

    db, err := sql.Open("sqlite3-hook", ":memory:")
    if err != nil {
        panic(err)
    }

    fmt.Println("tx1 (new)")
    tx1, _ := db.Begin()
    tx1.Rollback()

    fmt.Println("tx2 (reuse)")
    tx2, _ := db.Begin()

    fmt.Println("tx3 (new)")
    tx3, _ := db.Begin()
    tx2.Rollback()
    tx3.Rollback()

    if err = db.Close(); err != nil {
        panic(err)
    }
}
```

**Comment by nobonobo** [comment]
Thanks for a good solution.

**Pull request closed without merging**
